addition of asset.type
theodi/BDNS pull request #261
Opened 2024-07-17 10:21 UTC by pisuke

Addition of `asset.type` as discussed in #258 and #260

2024-07-17 10:41 UTC, RitaLav commented
@jgunstone @TheFridgeShaman @RitaLav 

To review and add comments

2024-07-17 11:26 UTC, RitaLav commented
Thought for consideration:

-  Repeat that Device/Asset type (asset.type) is entirely optional anywhere where it is mentioned so that the fact that it is optional is not missed or misunderstood.

2024-07-18 13:33 UTC, jgunstone requested changes
hi - apologies I didn't make the meeting yesterday - I was fire-fighting some server issues! This looks great to me, I've made a minor comment about incorporating Device/Asset Type in the header definintions. Many Thanks

2024-07-18 13:33 UTC, jgunstone commented on BDNS_Specification_naming_syntax.md
add to definitions in "Purpose and scope" section:
* **Device/Asset Type**: a type of device that has been selected to achieve a specific function. A device type remains fixed (provided direct replacement) if the hardware is replaced. (This is an optional field).

2024-07-18 13:33 UTC, jgunstone commented on BDNS_Specification_naming_syntax.md
> +`Z `= <asset_type_incremental_number> (variable length, unique integer numbers by asset type in each building, non zero padded)
optional unique ...

2024-07-24 10:55 UTC, pisuke commented on BDNS_Specification_naming_syntax.md
> +`Z `= <asset_type_incremental_number> (variable length, unique integer numbers by asset type in each building, non zero padded)
Added as suggested

2024-07-24 10:55 UTC, pisuke commented on BDNS_Specification_naming_syntax.md
Added as suggested

2024-07-31 09:01 UTC, TheFridgeShaman approved these changes

2024-07-31 10:35 UTC, RitaLav approved these changes

2024-07-31 10:44 UTC, RitaLav approved these changes

2024-07-31 10:44 UTC, RitaLav commented
@jgunstone we have reviewed and approved - if you are happy with the PR we can merge to master.

2024-07-31 10:50 UTC, RitaLav commented
Once merged we can also do a version release.

2024-08-05 11:57 UTC, jgunstone approved these changes
this looks great and @pisuke incorporated the comments I had - 
sorry for holding this up - I was on holiday last week. 

thanks everyone

2024-08-05 11:57 UTC, merged